#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nginx-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/10-nginx ]; then
sleep 2

	### Force Reset Permissions for Security
        mkdir -p /www/logs/nginx
    	mkdir -p /tmp/nginx
        chown -R nginx /www/logs/nginx
        chown nginx /tmp/nginx
        mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [nginx] Starting nginx'
exec nginx

