#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nginx-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/10-nginx ]; then
	
    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [otrs-5] Starting nginx'
exec nginx

