#!/usr/bin/with-contenv bash

### Set Defaults
  CGI_TIMEOUT=${CGI_TIMEOUT:-"180"}
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-"2G"}
  

### Adjust NGINX Runtime Variables  
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<CGI_TIMEOUT>/$CGI_TIMEOUT/g" /etc/nginx/conf.d/default.conf


